# Generated by Django 2.1.2 on 2019-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thecontact',
            name='city',
        ),
        migrations.AddField(
            model_name='thecontact',
            name='city_addr',
            field=models.CharField(default='', max_length=50, verbose_name='所在地区'),
        ),
        migrations.AlterField(
            model_name='thecontact',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='name'),
        ),
    ]
